server:
  port: 8084

spring:
  application:
    name: notification
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5431/notification
    password: '1'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true