server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5431/fraud
    password: '1'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'